# This file is machine-generated - editing it directly is not advised

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[PushVectors]]
git-tree-sha1 = "c7466c767062fa922a1689390a8aadb138253ecf"
uuid = "36b54c61-190e-5a5f-82d5-6f0a962d7362"
version = "0.2.1"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StaticArrays]]
deps = ["LinearAlgebra", "Random", "Statistics"]
git-tree-sha1 = "1c61c3c73460e15d293f6e26fe9068ecb3cb58b6"
repo-rev = "master"
repo-url = "https://github.com/JuliaArrays/StaticArrays.jl.git"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "1.1.0"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[UniversalLogger]]
deps = ["Logging", "PushVectors"]
git-tree-sha1 = "d9433c480dd7e64c7f042cf2bfdd63e8f1d99be9"
repo-rev = "master"
repo-url = "https://github.com/Lyceum/UniversalLogger.jl.git"
uuid = "5c5e3362-9445-4819-9f95-51c44c51adeb"
version = "0.2.0"
