# This file is autogenerated, do not edit by hand!
{fetchgit}: {
  registryUrl = "https://github.com/JuliaRegistries/General.git";
  registryRev = "85aa97f9975c82d9a41ec4e92173c46b70d37922";
  registrySha256 = "06pl5pbhfympg4wpnv2h701hrcp7hjcnbmxdhfnhyjpvri3wrai2";
  rootPackages = ["ArgParse" "Dates" "GitCommand" "HTTP" "JSON" "TOML"];
  closure = [{
  name = "ArgParse";
  uuid = "c7e460c6-2fb9-53a9-8c5b-16f535851c63";
  path = "A/ArgParse";
  replaceUrlInManifest = null;
  treehash = "3102bce13da501c9104df33549f511cd25264d7d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/carlobaldassi/ArgParse.jl.git"; rev = "3102bce13da501c9104df33549f511cd25264d7d"; sha256 = "02r4b0zj3cll0s7gpy2g6nya0s0rl7h337dqa9w2glmd3av3a4x8"; };
} {
  name = "Artifacts";
  uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33";
  path = "A/Artifacts";
  replaceUrlInManifest = null;
  treehash = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Artifacts.jl.git"; rev = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744"; sha256 = "0i0s26ypiwg6zyb3aqn9kiyiblkkab1mfac9plmq2jv4hggm4jfc"; };
} {
  name = "Base64";
  uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Dates";
  uuid = "ade2ca70-3891-5945-98fb-dc099432e06a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Distributed";
  uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Expat_jll";
  uuid = "2e619515-83b5-522b-bb60-26c02a35a201";
  path = "E/Expat_jll";
  replaceUrlInManifest = null;
  treehash = "1402e52fcda25064f51c77a9655ce8680b76acf0";
  artifacts = {
    "f371e7030764d7d3b86474ca985d35b87195302b" = [{
      name = "Expat";
      url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl/releases/download/Expat-v2.2.7+5/Expat.v2.2.7.x86_64-linux-gnu.tar.gz";
      sha256 = "6c67a9c49882e7ee51762368aa16b2a96d1e276289e1a7f8427525105ac458b0";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl.git"; rev = "1402e52fcda25064f51c77a9655ce8680b76acf0"; sha256 = "01g1wiyl6s9558s9im2ird0q18cvq98mvhn6ipjh9kb1v73khzd2"; };
} {
  name = "Gettext_jll";
  uuid = "78b55507-aeef-58d4-861c-77aaff3498b1";
  path = "G/Gettext_jll";
  replaceUrlInManifest = null;
  treehash = "8c14294a079216000a0bdca5ec5a447f073ddc9d";
  artifacts = {
    "93d795500c7b63f53b10478c17435f32e7a3c443" = [{
      name = "Gettext";
      url = "https://github.com/JuliaBinaryWrappers/Gettext_jll.jl/releases/download/Gettext-v0.20.1+5/Gettext.v0.20.1.x86_64-linux-gnu.tar.gz";
      sha256 = "cbb7caae1f685c65d681b606a814cadc6040d1414276d37b3d5e66d2e6d3ca7b";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Gettext_jll.jl.git"; rev = "8c14294a079216000a0bdca5ec5a447f073ddc9d"; sha256 = "1k6l48sr7dvfjp96lqabcqnxjjsx4cq7bdvn131gys0n2j954f2y"; };
} {
  name = "GitCommand";
  uuid = "49b5b516-ca3f-4003-a081-42bdcf55082d";
  path = "G/GitCommand";
  replaceUrlInManifest = null;
  treehash = "251953ec71a5b6994bcb4129416682ad8d34bb46";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaVersionControl/GitCommand.jl.git"; rev = "251953ec71a5b6994bcb4129416682ad8d34bb46"; sha256 = "1y3a5h2ljkd5rq8g85b35jqq5z47991w9yqigwlbfs78szssh3hq"; };
} {
  name = "Git_jll";
  uuid = "f8c6e375-362e-5223-8a59-34ff63f689eb";
  path = "G/Git_jll";
  replaceUrlInManifest = null;
  treehash = "424f3de127fac4d3c464eed1e08dab98af63c880";
  artifacts = {
    "1a282bd519cf6b811b315d6f27758fa013987ddc" = [{
      name = "Git";
      url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl/releases/download/Git-v2.27.0+0/Git.v2.27.0.x86_64-linux-gnu.tar.gz";
      sha256 = "4fed414814a48e1a4e1761210172e9cea195d6004c28444e65063cd171515ef9";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl.git"; rev = "424f3de127fac4d3c464eed1e08dab98af63c880"; sha256 = "1yx7jfzg2d22mpxiqqvb8mbp1nlw1hsdwhas8x7hqa3x7a3kzlps"; };
} {
  name = "HTTP";
  uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3";
  path = "H/HTTP";
  replaceUrlInManifest = null;
  treehash = "c9f380c76d8aaa1fa7ea9cf97bddbc0d5b15adc2";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/HTTP.jl.git"; rev = "c9f380c76d8aaa1fa7ea9cf97bddbc0d5b15adc2"; sha256 = "1qb4dr85w2f9fqzilm7wmr9nbihmsli92fmwafwfsg79bqnb45qh"; };
} {
  name = "IniFile";
  uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f";
  path = "I/IniFile";
  replaceUrlInManifest = null;
  treehash = "098e4d2c533924c921f9f9847274f2ad89e018b8";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/IniFile.jl.git"; rev = "098e4d2c533924c921f9f9847274f2ad89e018b8"; sha256 = "19cn41w04hikrqdzlxhrgf21rfqhkvj9x1zvwh3yz9hqbf350xs9"; };
} {
  name = "InteractiveUtils";
  uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "JLLWrappers";
  uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210";
  path = "J/JLLWrappers";
  replaceUrlInManifest = null;
  treehash = "642a199af8b68253517b80bd3bfd17eb4e84df6e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/JLLWrappers.jl.git"; rev = "642a199af8b68253517b80bd3bfd17eb4e84df6e"; sha256 = "0v7xhsv9z16d657yp47vgc86ggc01i1wigqh3n0d7i1s84z7xa0h"; };
} {
  name = "JSON";
  uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6";
  path = "J/JSON";
  replaceUrlInManifest = null;
  treehash = "81690084b6198a2e1da36fcfda16eeca9f9f24e4";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/JSON.jl.git"; rev = "81690084b6198a2e1da36fcfda16eeca9f9f24e4"; sha256 = "1f9k613kbknmp4fgjxvjaw4d5sfbx8a5hmcszmp1w9rqfqngjx9m"; };
} {
  name = "LibCURL_jll";
  uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0";
  path = "L/LibCURL_jll";
  replaceUrlInManifest = null;
  treehash = "897d962c20031e6012bba7b3dcb7a667170dad17";
  artifacts = {
    "904600d991a748e89b4272f20181157c1bdf0d94" = [{
      name = "LibCURL";
      url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.x86_64-linux-gnu.tar.gz";
      sha256 = "e5245329f781e7c2495383403ce489d984cee24801b4bc6b9f853124e6df083d";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl.git"; rev = "897d962c20031e6012bba7b3dcb7a667170dad17"; sha256 = "1d3ci6j0gplg2iq7y74cla6h0imjkqz3qzgc6sjnglb4pmgwqk9b"; };
} {
  name = "LibGit2";
  uuid = "76f85450-5226-5b5a-8eaa-529ad045b433";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LibSSH2_jll";
  uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8";
  path = "L/LibSSH2_jll";
  replaceUrlInManifest = null;
  treehash = "717705533148132e5466f2924b9a3657b16158e8";
  artifacts = {
    "6d4906ad8a52d22b3cf4e9e104a46e7c3d4c5fa5" = [{
      name = "LibSSH2";
      url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.x86_64-linux-gnu.tar.gz";
      sha256 = "b6dac664fc38fca7b9efc937bb182a147a145f4fa5a387c1cc5a21633b3c8ec0";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl.git"; rev = "717705533148132e5466f2924b9a3657b16158e8"; sha256 = "1702lkphkw3c89vq0p49jrn8yjp187kynqcv93n912fcz23jl25s"; };
} {
  name = "Libdl";
  uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libiconv_jll";
  uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531";
  path = "L/Libiconv_jll";
  replaceUrlInManifest = null;
  treehash = "8e924324b2e9275a51407a4e06deb3455b1e359f";
  artifacts = {
    "473dc2ed3d46252c87733b7fdca3da64c6f9f917" = [{
      name = "Libiconv";
      url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+5/Libiconv.v1.16.0.x86_64-linux-gnu.tar.gz";
      sha256 = "518b0c2f04ba6057dc5ed63f4dc23e4abac49840b6b5470ce8cf1ad8412c6227";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl.git"; rev = "8e924324b2e9275a51407a4e06deb3455b1e359f"; sha256 = "07xd1lbp8ldavxpik9h40wx80mfaf0isz9jza4g7xgfcbyfqh1d8"; };
} {
  name = "Logging";
  uuid = "56ddb016-857b-54e1-b83d-db4d58db5568";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Markdown";
  uuid = "d6f4376e-aef5-505a-96c1-9c027394607a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MbedTLS";
  uuid = "739be429-bea8-5141-9913-cc70e7f3736d";
  path = "M/MbedTLS";
  replaceUrlInManifest = null;
  treehash = "1c38e51c3d08ef2278062ebceade0e46cefc96fe";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/MbedTLS.jl.git"; rev = "1c38e51c3d08ef2278062ebceade0e46cefc96fe"; sha256 = "0zjzf2r57l24n3k0gcqkvx3izwn5827iv9ak0lqix0aa5967wvfb"; };
} {
  name = "MbedTLS_jll";
  uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1";
  path = "M/MbedTLS_jll";
  replaceUrlInManifest = null;
  treehash = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6";
  artifacts = {
    "519367e9365948074c1fcc9f4365597f147a5ab7" = [{
      name = "MbedTLS";
      url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.8+0/MbedTLS.v2.16.8.x86_64-linux-gnu.tar.gz";
      sha256 = "5968d98ac1d4fdbf44ed87b0687f916f69ab077961b3cc9ea6068e2d739bd953";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl.git"; rev = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6"; sha256 = "0x43cp26p4w799i1cy4j72l5b1dyqcsab98qjw6yydxk2wha5vw4"; };
} {
  name = "Mmap";
  uuid = "a63ad114-7e13-5084-954f-fe012c677804";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "NetworkOptions";
  uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908";
  path = "N/NetworkOptions";
  replaceUrlInManifest = null;
  treehash = "ed3157f48a05543cce9b241e1f2815f7e843d96e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/NetworkOptions.jl.git"; rev = "ed3157f48a05543cce9b241e1f2815f7e843d96e"; sha256 = "02nm4v67lb1dzhgyyr9bg8kylyyhsgfsxf3nxhbl4hp9dz48an0a"; };
} {
  name = "OpenSSL_jll";
  uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95";
  path = "O/OpenSSL_jll";
  replaceUrlInManifest = null;
  treehash = "71bbbc616a1d710879f5a1021bcba65ffba6ce58";
  artifacts = {
    "e6e5f41352118bbeb44677765ebccab8c151c72a" = [{
      name = "OpenSSL";
      url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v1.1.1+2/OpenSSL.v1.1.1.x86_64-linux-gnu.tar.gz";
      sha256 = "77be5b30230b67396a691ba8be144824b515e8ea5070df7bd5b06026fdc5ca56";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl.git"; rev = "71bbbc616a1d710879f5a1021bcba65ffba6ce58"; sha256 = "15317wll2b1nks8ayg633ar8d9n3sil2nn4rrx165jdgsf2zndij"; };
} {
  name = "PCRE2_jll";
  uuid = "efcefdf7-47ab-520b-bdef-62a2eaa19f15";
  path = "P/PCRE2_jll";
  replaceUrlInManifest = null;
  treehash = "0e1d7a0fa3326a1cd9ec4738f806b24df99a99f4";
  artifacts = {
    "1ccb8a00f18445a3ca3d2a9e64da7e2a5f1fc61b" = [{
      name = "PCRE2";
      url = "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl/releases/download/PCRE2-v10.34.0+2/PCRE2.v10.34.0.x86_64-linux-gnu.tar.gz";
      sha256 = "e62f3c084e7b446d7ae0fafa89acc008771c2358f9298ded4f5ad100ac9a4fc0";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/PCRE2_jll.jl.git"; rev = "0e1d7a0fa3326a1cd9ec4738f806b24df99a99f4"; sha256 = "1n7z2yk8i9pbm69q0rpbs5whcnn7h2j39h2k3hy8xw3lfa7imbkb"; };
} {
  name = "Parsers";
  uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0";
  path = "P/Parsers";
  replaceUrlInManifest = null;
  treehash = "c8abc88faa3f7a3950832ac5d6e690881590d6dc";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Parsers.jl.git"; rev = "c8abc88faa3f7a3950832ac5d6e690881590d6dc"; sha256 = "1gz3drd5334xrbx2ms33hiifkd0q1in4ywc92xvrkq3xgzdjqjdk"; };
} {
  name = "Pkg";
  uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Preferences";
  uuid = "21216c6a-2e73-6563-6e65-726566657250";
  path = "P/Preferences";
  replaceUrlInManifest = null;
  treehash = "ea79e4c9077208cd3bc5d29631a26bc0cff78902";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Preferences.jl.git"; rev = "ea79e4c9077208cd3bc5d29631a26bc0cff78902"; sha256 = "010bn42gqj81j2bi7zswfvh0g74g2pj28iqhncnpnhfg9znsp0li"; };
} {
  name = "Printf";
  uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "REPL";
  uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Random";
  uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "ReplMaker";
  uuid = "b873ce64-0db9-51f5-a568-4457d8e49576";
  path = "R/ReplMaker";
  replaceUrlInManifest = null;
  treehash = "76098218397ec93b925b70ce355144d539b1a8b4";
  artifacts = {};
  src = fetchgit { url = "https://github.com/MasonProtter/ReplMaker.jl.git"; rev = "76098218397ec93b925b70ce355144d539b1a8b4"; sha256 = "00l61f4yckcb31h4dnmajckhvjbgyxz373i57kmwrad5k269piyx"; };
} {
  name = "SHA";
  uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce";
  path = "S/SHA";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Serialization";
  uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Sockets";
  uuid = "6462fe0b-24de-5631-8697-dd941f90decc";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "TOML";
  uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76";
  path = "T/TOML";
  replaceUrlInManifest = null;
  treehash = "44aaac2d2aec4a850302f9aa69127c74f0c3787e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/TOML.jl.git"; rev = "44aaac2d2aec4a850302f9aa69127c74f0c3787e"; sha256 = "1xy19fc5lrj9kh298xhczvmjl1cx3p46fj2xlmkisaqxzhd782yd"; };
} {
  name = "Test";
  uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "TextWrap";
  uuid = "b718987f-49a8-5099-9789-dcd902bef87d";
  path = "T/TextWrap";
  replaceUrlInManifest = null;
  treehash = "9250ef9b01b66667380cf3275b3f7488d0e25faf";
  artifacts = {};
  src = fetchgit { url = "https://github.com/carlobaldassi/TextWrap.jl.git"; rev = "9250ef9b01b66667380cf3275b3f7488d0e25faf"; sha256 = "1nlhi9f9y6nmnjq1z9d60ql39ajpbgc93ji0z7blnddyf48i6zdy"; };
} {
  name = "URIs";
  uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4";
  path = "U/URIs";
  replaceUrlInManifest = null;
  treehash = "7855809b88d7b16e9b029afd17880930626f54a2";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaWeb/URIs.jl.git"; rev = "7855809b88d7b16e9b029afd17880930626f54a2"; sha256 = "0fqyagsqks5za7m0czafr34m2xh5501f689k9cn5x3npajdnh2r3"; };
} {
  name = "UUIDs";
  uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Unicode";
  uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "XML2_jll";
  uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a";
  path = "X/XML2_jll";
  replaceUrlInManifest = null;
  treehash = "be0db24f70aae7e2b89f2f3092e93b8606d659a6";
  artifacts = {
    "595a9c11691838de1f6ed43bfe902f7885cb366a" = [{
      name = "XML2";
      url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.9.10+0/XML2.v2.9.10.x86_64-linux-gnu.tar.gz";
      sha256 = "5cf1af4a89abb666b0fbafa07fd3748dc05f36f6c57756c8b666f75ec2f0e96b";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl.git"; rev = "be0db24f70aae7e2b89f2f3092e93b8606d659a6"; sha256 = "187acynbivka91dx91qar55dc5zjy3sqi32v4f3p9avhk48i4w97"; };
} {
  name = "Zlib_jll";
  uuid = "83775a58-1f1d-513f-b197-d71354ab007a";
  path = "Z/Zlib_jll";
  replaceUrlInManifest = null;
  treehash = "320228915c8debb12cb434c59057290f0834dbf6";
  artifacts = {
    "27bce23cfb763bc3cc8ccba62ee0a8f67b6f9d9e" = [{
      name = "Zlib";
      url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+13/Zlib.v1.2.11.x86_64-linux-gnu.tar.gz";
      sha256 = "864b11412f28af74c440488cfec2fa0782529f507177c49dddda54eb01185449";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl.git"; rev = "320228915c8debb12cb434c59057290f0834dbf6"; sha256 = "0f0dznr9y5zq1yllin61v7qlk8qhac0n71vkmylsjb7bvc77136w"; };
} {
  name = "nghttp2_jll";
  uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d";
  path = "N/nghttp2_jll";
  replaceUrlInManifest = null;
  treehash = "8e2c44ab4d49ad9518f359ed8b62f83ba8beede4";
  artifacts = {
    "866d2adc53c818f1fedc9d9bfd0d03126572f5cd" = [{
      name = "nghttp2";
      url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.x86_64-linux-gnu.tar.gz";
      sha256 = "3aa3cdee9aea6165186635a9fb21ff1ff9064ef24b9f7adfdc5ff39b86f4face";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl.git"; rev = "8e2c44ab4d49ad9518f359ed8b62f83ba8beede4"; sha256 = "014pizanicivwsy4fdcm60mx9g8s9wqdzlsprrv2ga45qda6rcs4"; };
}];
}
