name: CI
on:
  - push
  - pull_request
  - workflow_dispatch 
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: 
          - "1"
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            cores = 0
            max-jobs = auto
            http-connections = 100
            experimental-features = nix-command flakes
    
      - name: Install nixUnstable
        run: |
          nix-env -iA nixUnstable -f '<nixpkgs>'
          echo "${HOME}/.nix-profile/bin" >> $GITHUB_PATH

      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      
      - run: nix run .#test 
