name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            cores = 0
            max-jobs = auto
            experimental-features = nix-command flakes
            extra-sandbox-paths = /var/cache/ccache=/var/cache/ccache
            log-lines = 200
            http-connections = 100
            access-tokens = github.com=${{ secrets.PAT }}
      
      - name: Setup CCache
        run: |
          sudo mkdir -m0770 /var/cache/ccache
          sudo chown root:nixbld /var/cache/ccache

      - uses: cachix/cachix-action@v10
        with:
          name: colinxs
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community
          pushFilter: '.*(-source|-nixpkgs\.tar\.gz|-nixpkgs-[0-9]{2}\.[0-9]{2}.*)$'
      
      - name: Nix Info 
        run: |
          echo "===================="
          nix --version
          echo
          nix show-config
          echo
          env
          echo "===================="

      # - name: Fix GITHUB_PATH 
      #   run: |
      #     echo "${HOME}/.nix-profile/bin" >> $GITHUB_PATH

      - name: Build 
        run: nix build .#run-test 
      
      - name: Test
        run: nix run .#run-test 
      
      - name: Flake Check 
        run: nix flake check 

      - name: GC Store
        run: nix store gc
