name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.julia/artifacts
            ~/.julia/packages
          key: ${{ hashFiles('./nix-home/**/Project.toml') }}-${{ hashFiles('./nix-home/**/Manifest.toml') }}
          restore-keys: |
            ${{ hashFiles('./nix-home/**/Project.toml') }}-

      - uses: cachix/install-nix-action@v14
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            cores = 0
            max-jobs = auto
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.PAT }}

      - uses: cachix/cachix-action@v10
        with:
          name: colinxs
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community
          pushFilter: '.*(-source|-nixpkgs\.tar\.gz|-nixpkgs-[0-9]{2}\.[0-9]{2}.*)$'

      - name: Install nix_2_4
        run: |
          nix-env -iA nix_2_4 -f '<nixpkgs>'
          echo "${HOME}/.nix-profile/bin" >> $GITHUB_PATH
      
      - name: Build 
        run: nix build .#run-test 
      
      - name: Test
        run: nix run .#run-test 
      
      - name: Flake Check 
        run: nix flake check 

      - name: GC Store
        run: nix store gc
