name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            cores = 0
            max-jobs = auto
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.PAT }}

      - uses: cachix/cachix-action@v10
        with:
          name: colinxs
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community

      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.julia/artifacts
            ~/.julia/packages
          key: ${{ hashFiles('./nix-home/**/Manifest.toml') }}

      - name: Install nixUnstable
        run: |
          nix-env -iA nixUnstable -f '<nixpkgs>'
          echo "${HOME}/.nix-profile/bin" >> $GITHUB_PATH
      
      - name: Run Test
        run: nix run .#run-test 
