name: CI
on:
  - push
  - pull_request
  - workflow_dispatch 
jobs:
  test:
    name: ${{ github.event_name }}
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2.3.4
      
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.julia/artifacts
            ~/.cache/nix
          key: ${{ runner.os }}-${{ hashFiles('**/Project.toml','**/flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            cores = 0
            max-jobs = auto
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.PAT }}
    
      - name: Install nixUnstable
        run: |
          nix-env -iA nixUnstable -f '<nixpkgs>'
          echo "${HOME}/.nix-profile/bin" >> $GITHUB_PATH

      - name: Run Test
        run: nix run .#test 
