name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            cores = 0
            max-jobs = auto
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.PAT }}

      - uses: cachix/cachix-action@v10
        with:
          name: colinxs
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community

      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.julia/artifacts
            ~/.julia/packages
          key: ${{ hashFiles('**/Manifest.toml') }}

      - name: Install nixUnstable
        run: |
          nix-env -iA nixUnstable -f '<nixpkgs>'
          echo "${HOME}/.nix-profile/bin" >> $GITHUB_PATH

      - name: Update
        run: |
          nix --version
          echo "NIX_PATH: $NIX_PATH"
          nix run github:colinxs/NixSourcerer.jl -- --recursive --workers 4
        env:
          JULIA_DEBUG: NixSourcerer

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.9.1
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: updates
          delete-branch: true
      
      - name: GC Store
        run: nix store gc
