name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1,3,5" # Every Mon/Wed/Fri at 0800

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            cores = 0
            max-jobs = auto
            experimental-features = nix-command flakes
            extra-sandbox-paths = /var/cache/ccache=/var/cache/ccache
            log-lines = 200
            http-connections = 100
            access-tokens = github.com=${{ secrets.PAT }}

      - name: Setup CCache
        run: |
          sudo mkdir -m0770 /var/cache/ccache
          sudo chown root:nixbld /var/cache/ccache

      - uses: cachix/cachix-action@v10
        with:
          name: colinxs
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community
          pushFilter: '.*(-source|-nixpkgs\.tar\.gz|-nixpkgs-[0-9]{2}\.[0-9]{2}.*)$'
      
      - name: Nix Info 
        run: |
          echo "===================="
          nix --version
          echo
          nix show-config
          echo
          env
          echo "===================="

      # - name: Fix GITHUB_PATH 
      #   run: |
      #     echo "${HOME}/.nix-profile/bin" >> $GITHUB_PATH

      - name: Update
        run: nix run .#nix-sourcerer -- --workers 4 --verbose --recursive

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: updates
          delete-branch: true
      
      - name: GC Store
        run: nix store gc
